---
# vars file for vsftpd
services:
  - vsftpd
  - firewalld

dirs:
  pub: 
    dir: /var/ftp/pub 
    mode: 0754
  upload: 
    dir: /var/ftp/pub/upload
    mode: 0755
 
vsftpd_anonymous_enable: YES
vsftpd_anon_upload_enable: YES
vsftpd_local_enable: NO
vsftpd_listen: YES
vsftpd_listen_ipv6: NO