---
# tasks file for vsftpd
- name: Ensure vsftpd and firewalld are presented
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ services }}"

- name: "Ensure pakeges for selinux presented"
  yum:
    name: 
      - python3-libsemanage
      - policycoreutils-python-utils
    state: present
  when: ansible_distribution == "CentOS"
  
- name: Ensure services is started
  service:
    name: "{{ item }}"
    state: started
  with_items: "{{ services }}"

- name: Debug message
  debug:
    msg: "{{ item.value.dir }}"
  with_dict: "{{ dirs }}"

- name: Ensure needed dir presented
  file:
    path: "{{ item.value.dir }}"
    state: directory
    owner: ftp
    group: ftp
    mode: "{{ item.value.mode }}"
    setype: "{{ item.value.setype }}"
  with_dict: "{{ dirs }}"

- name: Esure vsftpd.conf file is presented
  template:
    src: vsftpd.conf.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: 
    - reload_vsftpd

- name: Ensure selinuxe is adjusted
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes

- name: Ensure firewall allowed connection
  firewalld:
    port: 20-21/tcp
    state: enabled
